### PR TITLE
Use pathlib.Path instead of os.path

### PR DESCRIPTION
**Pull request by PrimePlaya24**
Implementation to use pathlib.Path to fulfill issue #20 

Still need to run tests to make sure.

### CODE REVIEW

**Comment by jslay88** [comment]
Sweet. I'll start working on integrating this into a `pathlib` branch that replaces all of `os` hopefully. 

Also, you should set your git config email and username, cause your commits are linking to no user (should see your avatar next to your commits). I want to make sure I can give you contribution accordingly.

**Comment by PrimePlaya24** [comment]
Running on a Unix machine:
```bash
>>> import pathlib
>>> pathlib.PurePath(pathlib.Path.cwd())
PurePosixPath('/home/user/')
```
Running on a Windows machine:
```bash
>>> import pathlib
>>> pathlib.PurePath(pathlib.Path.cwd())
PureWindowsPath('C:/Users/user')
```

So we can let the `pathlib` module determine the correct Path to use if we want, otherwise we can do it manually using the sys module or whichever.

P.S. I will configure my commits correctly based on the info provided, thank you!

**Comment by PrimePlaya24** [comment]
Mainly we need to target the right filesystem for the target OS. So that is where the above function comes in. I see that now. 👍

**Comment by jslay88** [comment]
Superseded by #53

**Pull request closed without merging**
